apiVersion: v1
kind: Deployment
metadata:
  name: testapp1
  labels:
    app.kubernetes.io/instance: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: test
    spec:
      containers:
      - name: testapp1
        image: tomerle03/test-argo:latest
        imagePullPolicy: Always
