apiVersion: v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app.kubernetes.io/instance: test
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: test
    spec:
      containers:
      - name: testapp
        image: tomerle03/test-argo:latest
        imagePullPolicy: Always
