apiVersion: v1
kind: Pod
metadata:
  name: testapp
  labels:
    app.kubernetes.io/instance: test
spec:
  containers:
  - name: testapp
    image: rapidfort/flaskapp:latest
    imagePullPolicy: Always
    resources:
      limits:
        memory: "200Mi"
