apiVersion: v1
kind: Pod
metadata:
  name: testapp
spec:
  containers:
  - name: testapp
    image: rapidfort/flaskapp:latest
    imagePullPolicy: Always
    resources:
      limits:
        memory: "200Mi"
