apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app.kubernetes.io/instance: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: testapp
        image: tomerle03/test-argo:latest
        imagePullPolicy: Always
